### ISSUE TITLE
/etc/squid3/ doesn't exist in the squid v3 package in ubuntu 1604 repo

### ISSUE THREAD

**Issue by troydsmith** [rdmcgregor/puppet-squid#1]
/etc/squid3/ is no longer the dir where squid.conf resides,
/etc/squid/ is created on installation of squid 3.5.12-1 on ubuntu amd64

# dpkg --list
squid          3.5.12-1ubun amd64        Full featured Web Proxy cache (HT

# ll /etc/
drwxr-xr-x  2 root root    4096 Feb  7 12:12 squid/

# find /etc/squid
/etc/squid
/etc/squid/errorpage.css
/etc/squid/squid.conf

**Comment by rdmcgregor** [comment]
Config path has been updated, also original module is available as Tag 0.1.0
